### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by LCHansson** [LCHansson/ggplot_interactive#2]
- [ ] Floating div instead of toggle-through selection
- [ ] Add element
- [ ] Add parameters to elements
- [ ] Download plot + code
- [ ] Add aes parameter
- [ ] Invalidate aes parameters
- [ ] Remove element
- [ ] Remove parameter
- [ ] Toggle aes parameter
- [ ] Contextualise argument values for aes
- [ ] Contextualise argument values for parameters (is this even possible?)
- [ ] Input fields as last resort when assigning argument values
### Wishlist
- [ ] Save/share plot code
- [ ] Paste/parse plot code
